# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:calculadoradb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Console H2: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
